name: Test
on: [ push ]
jobs:
  build:
    name: Build, Test, Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Test
        run: python -m unittest discover glyphs/tests


